feat: 🎸 verify update setup py

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,6 +3,7 @@ image: nikolaik/python-nodejs:python3.11-nodejs20
 
 stages:
   - build
+  - test
 
 build:
   stage: build
@@ -10,4 +11,19 @@ build:
   - pip install -e .
   - npm install -g remark-cli
   - npm install -g remark-directive
+
+test:
+  stage: test
+  script:
   - pytest -v -s .
+
+setup_py:
+  stage: test
+  script:
+  - |
+    if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_REF_NAME | grep -q '^setup\.py$'; then
+      echo "setup.py file has changed."
+    else
+      echo "No changes in setup.py file. CI will fail."
+      exit 1
+    fi
